-- Spusť celý tento skript v Supabase:
-- SQL Editor > New query > vložit > Run

create table if not exists public.activity_log (
    id bigint generated by default as identity primary key,
    employee_id text not null,
    employee_name text not null,
    activity text not null check (
        activity in ('Aperam', 'Personna', 'SSI', 'Zanini', 'Rebound')
    ),
    start_time timestamptz not null default now(),
    end_time timestamptz,
    duration_seconds integer,
    created_at timestamptz not null default now(),

    constraint end_after_start check (
        end_time is null or end_time >= start_time
    ),
    constraint duration_nonnegative check (
        duration_seconds is null or duration_seconds >= 0
    )
);

-- Jeden pracovník může mít současně jen jednu rozpracovanou činnost.
create unique index if not exists one_active_activity_per_employee
on public.activity_log (employee_id)
where end_time is null;

create index if not exists activity_log_start_time_idx
on public.activity_log (start_time desc);

alter table public.activity_log enable row level security;

drop policy if exists "activity_log_select" on public.activity_log;
drop policy if exists "activity_log_insert" on public.activity_log;
drop policy if exists "activity_log_update" on public.activity_log;

-- Aplikace používá anon key uložený bezpečně ve Streamlit Secrets.
-- Tyto politiky dovolí aplikaci záznamy číst, přidávat a ukončovat.
create policy "activity_log_select"
on public.activity_log
for select
to anon
using (true);

create policy "activity_log_insert"
on public.activity_log
for insert
to anon
with check (
    employee_id <> ''
    and employee_name <> ''
    and activity in ('Aperam', 'Personna', 'SSI', 'Zanini', 'Rebound')
    and end_time is null
    and duration_seconds is null
);

create policy "activity_log_update"
on public.activity_log
for update
to anon
using (end_time is null)
with check (
    end_time is not null
    and duration_seconds is not null
    and duration_seconds >= 0
);
